name: Terraform AWS Workflow

on:
  push:
    branches:
      - main

jobs:
  tf_code_check:
    name: Terraform Validation and Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/terraform
    outputs:
      output1: ${{ steps.Call_terraform_output.outputs.distro }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false

    - name: Initialize Terraform
      run: terraform init

    - name: Generate Terraform Plan
      run: terraform plan -out=tfplan
      
    - name: Apply Terraform Changes
      run: |
        terraform apply tfplan
      if: success()
      
    - name: Sync S3 1
      uses: jakejarvis/s3-sync-action@master
      env:
        SOURCE_DIR: 'src/'
        AWS_REGION: 'us-east-1'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Sync S3 2
      uses: jakejarvis/s3-sync-action@master
      env:
        SOURCE_DIR: 'src/'
        AWS_REGION: 'us-east-1'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_2 }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Sync S3 3
      uses: jakejarvis/s3-sync-action@master
      env:
        SOURCE_DIR: '/*'
        AWS_REGION: 'us-east-1'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_3 }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Sync S3 4
      uses: jakejarvis/s3-sync-action@master
      env:
        SOURCE_DIR: '/*'
        AWS_REGION: 'us-east-1'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_4 }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
