name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  da_job:

    name: Deploy Site
    runs-on: ubuntu-latest
    
  
    steps:

    - uses: hashicorp/setup-terraform@v2

    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        path: '$home/repo'

    - name: Terraform fmt
      id: fmt
      run: |
        cd $home/repo \
        terraform fmt -check
      continue-on-error: true
   
    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color


    - name: Terraform Apply
      run: terraform apply

    - name: Sync S3
      uses: jakejarvis/s3-sync-action@master
      
