name: Terraform AWS Workflow

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tfpath:
        description: 'TF File Path'     
        required: false
        default: 'terraform/'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tf_code_check:
    name: Terraform Validation and Build
    runs-on: ubuntu-latest

    if:  ${{ inputs.tfpath }} 
    steps:
    - uses: actions/checkout@v3
    

    - name: Configure AWS Credentials Action For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2.0.2

    - name: Terraform init, plan and apply
      run: |
        echo "** Running Terraform Init**"
        terraform -chdir=main/${{ github.event.inputs.tfpath }} init -reconfigure -input=false
        
        echo "** Running Terraform Validate**"
        terraform -chdir=main/${{ github.event.inputs.tfpath }} validate
        
        echo "** Running Terraform Plan**"
        terraform -chdir=main/${{ github.event.inputs.tfpath }} plan -var-file="../../terraform/terraform.tfvars"
        
        echo "** Running Terraform Apply**"
        terraform -chdir=main/${{ github.event.inputs.tfpath }} apply -auto-approve
    - name: Terraform Destroy
      run: |
        echo "** Running Terraform Destroy**"
        terraform plan -destroy
        terraform destroy -auto-approve
      working-directory: ${{ github.event.inputs.tfpath }}

    - name: Sync S3
      uses: jakejarvis/s3-sync-action@master
      env:
        SOURCE_DIR: 'src/'
        AWS_REGION: 'us-east-1'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
