name: Terraform AWS Workflow
on:
  push:
    branches:
      - main
jobs:
  tf_code_check:
    name: Terraform Validation and Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/terraform
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Inject build date
      working-directory: ${{ github.workspace }}
      run: |
        BUILD_DATE=$(date +'%B %Y')
        sed -i "s|<meta name=\"build-date\" content=\"[^\"]*\">||g" src/index.html
        sed -i "s|</head>|<meta name=\"build-date\" content=\"$BUILD_DATE\">\n</head>|" src/index.html

    - name: Zip and hash Lambda function
      working-directory: ${{ github.workspace }}/terraform/backend
      run: |
        zip -j visitor_count.zip visitor_count.mjs
        aws s3 cp visitor_count.zip s3://connersmith.net.repo/visitor_count
        HASH=$(openssl dgst -sha256 -binary visitor_count.zip | openssl enc -base64)
        echo "LAMBDA_HASH=$HASH" >> $GITHUB_ENV
        echo "Hash computed: $HASH"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    - name: Initialize Terraform
      run: terraform init -upgrade

    - name: Generate Terraform Plan
      run: terraform plan -out=tfplan -var="lambda_source_code_hash=${{ env.LAMBDA_HASH }}"

    - name: Apply Terraform Changes
      run: terraform apply tfplan

    - name: Sync site to S3 (primary bucket)
      uses: jakejarvis/s3-sync-action@v0.5.1
      env:
        SOURCE_DIR: 'src/'
        AWS_REGION: 'us-east-1'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Sync site to S3 (www bucket)
      uses: jakejarvis/s3-sync-action@v0.5.1
      env:
        SOURCE_DIR: 'src/'
        AWS_REGION: 'us-east-1'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_2 }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
          --paths "/*"